/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const boot: () => void;
export const button: (a: number, b: number, c: number, d: number) => void;
export const hud: (a: number, b: number) => [number, number];
export const init: (a: number, b: number, c: number, d: number, e: number) => void;
export const key: (a: number, b: number, c: number, d: number, e: number) => void;
export const net_close: (a: number, b: number) => void;
export const net_open: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const net_status: (a: number, b: number) => [number, number];
export const pointer: (a: number, b: number, c: number, d: number) => void;
export const running: (a: number, b: number) => number;
export const start: (a: number, b: number) => void;
export const tick: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h1640237add5a99b3: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h196b57bda68afff6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h196b57bda68afff6_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h196b57bda68afff6_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hed18c246d52ebd85: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h196b57bda68afff6_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h579fcc4fdc37a792: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
